services:
  globetalk-front:
    build:
      context: ../globetalk-front
      dockerfile: Dockerfile
    env_file:
      - ../globetalk-front/.env.production
    depends_on:
      - globetalk-back
    container_name: globetalk-front

  globetalk-back:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - ./.env.production 
    restart: always
    depends_on:
      - mongo
    container_name: globetalk-back

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certdata:/etc/letsencrypt
    depends_on:
      - globetalk-back
      - globetalk-front
      - globetalk-nlp-nllb
    container_name: nginx

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=globetalk
    volumes:
      - mongodb_data:/data/db
    container_name: mongo

  portfolio:
    build:
      context: ../portfolio
      dockerfile: Dockerfile
    container_name: portfolio

  globetalk-nlp-nllb:
    build:
      context: ../globetalk-nlp-nllb   
      dockerfile: Dockerfile
    command: python app.py   
    expose:
      - "5000"  
    restart: always
    container_name: globetalk-nlp-nllb  

volumes:
  mongodb_data:
  certdata:
